spring:
  application:
    name: client1


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8887/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5
      
server:
  port: 8001      